on:
  workflow_call:
name: upload
runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Set tag env
    - name: Set tag env
      shell: bash
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Echo tag env
      shell: bash
      run: |
        echo ${{ env.RELEASE_TAG }}

    # Parse and set verstion and revision env from tag
    - id: parse-tags
      name: Parse tags
      uses: actions/github-script@v6
      shell: bash
      with:
        script: |
          const items = "${{ env.RELEASE_TAG }}".split('-')
          console.log(items)
          core.setOutput('version', items[0])
          core.setOutput('revision', items[1])
    - name: Set version env
      shell: bash
      run: echo "RELEASE_VERSION=${{steps.parse-tags.outputs.version}}" >> $GITHUB_ENV
    - name: Set revision env
      shell: bash
      run: echo "RELEASE_REVISON=${{steps.parse-tags.outputs.revision}}" >> $GITHUB_ENV

    # Runs uploading a spec to API registry
    # - name: Upload specs
      # shell: bash
    #   run: |
    #     echo Upload a spec to api registry
    #     ./.bin/apiregistryctl service uploadspec openapi/catalogue.json -s catalogue --version "${{ env.RELEASE_VERSION }}" --revision "${{ env.RELEASE_REVISON }}"
